version: "3.7"
services:
  app:
    build:
      args:
        user: lotustea
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: reparcelamento
    container_name: reparcelamento-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - reparcelamento

  db:
    image: mysql:5.7
    container_name: reparcelamento-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - reparcelamento

  nginx:
    image: nginx:1.17-alpine
    container_name: reparcelamento-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - reparcelamento

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - reparcelamento

networks:
  reparcelamento:
    driver: bridge
